### ISSUE TITLE
Bower dont find package

### ISSUE THREAD

**Issue by meron1122** [drmonty/datatables-plugins#1]
![gnnjgv1](https://cloud.githubusercontent.com/assets/2895090/6954660/7d803f7a-d8d4-11e4-9f8c-ce8bdd479278.png)

I'm doing something wrong?
    "drmonty-datatables-plugins": "1.10.*"

in bower.json

**Comment by drmonty** [comment]
Sorry, forgot to register this repository in bower, should now work :)
